### ISSUE TITLE
How to consume this?

### ISSUE THREAD

**Issue by clarkmcc** [space-nuko/litegraph.ts#1]
I tried the following but am getting. I guess this is because the package.json file doesn't have a `version` specified. Is there an alternative way to consume this lib?
```
$ yarn add https://github.com/space-nuko/litegraph.ts#master
yarn add v1.22.17
warning ../../../../../package.json: No license field
[1/4] 🔍  Resolving packages...
error Can't add undefined: invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by space-nuko** [comment]
Personally I cloned the repo as a submodule then added a `pnpm-workspace.yml`

```yaml
packages:
  - 'litegraph-ts/packages/*'
```

Inside `package.json` add the packages you want through the `workspace` directive

```json
{
  "dependencies": {
    "@litegraph-ts/core": "workspace:*",
    "@litegraph-ts/nodes-basic": "workspace:*",
    "@litegraph-ts/nodes-events": "workspace:*",
    "@litegraph-ts/nodes-logic": "workspace:*",
    "@litegraph-ts/nodes-math": "workspace:*",
    "@litegraph-ts/nodes-strings": "workspace:*",
    "@litegraph-ts/tsconfig": "workspace:*"
  }
}
```

Install with `pnpm`. Before all main application logic `import` the node packages to make sure they're registered

```ts
import "@litegraph-ts/nodes-basic";
import "@litegraph-ts/nodes-events";
import "@litegraph-ts/nodes-logic";
import "@litegraph-ts/nodes-math";
import "@litegraph-ts/nodes-strings";
```

From there you should be able to instantiate the included node classes, examples can be found in the repo: https://github.com/space-nuko/litegraph.ts/tree/master/apps

**Comment by clarkmcc** [comment]
Thanks
